name: Delete artifacts manually

# Run action manually
on:
  - workflow_dispatch

jobs:
  delete:
    name: Delete artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: artifact
        with:
          # Delete all artifacts
          script: |
            var page = 1;

            while (true) {
              console.log(`Page ${page}`);

              const res = await github.rest.actions.listArtifactsForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 100,
                page: 1,
              });

              console.log(`${res.data.artifacts.length} artifacts`);

              if (res.data.artifacts.length === 0) {
                break;
              }

              page++;

              res
                .data
                .artifacts
                .forEach(({ id, name, size_in_bytes }) => {
                  console.log(`Deleting artifact ID ${id}, name ${name}, ${size_in_bytes} bytes`);

                  github.rest.actions.deleteArtifact({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    artifact_id: id,
                  });
                });
            }
